steps:
  - name: Build Pipeline
    containerSet:
      containers:
      - name: Buildpack Build
        containerTemplate: choreo/buildpack-build@v1
      - name: Vulnerability Scan
        containerTemplate: choreo/trivy-scan@v1
      - name: Test
        containerTemplate: test-container
      - name: Lint
        containerTemplate: lint-container
  - name: Static Code Analysis
    template: sonar-qube
  - name: Post Build
    containerSet:
      containers:
      - name: Lint
        containerTemplate: lint-container-2
      - name: Lint 2
        containerTemplate: lint-container-3

templates:
  - name: sonar-qube
    inlineScript: |
      #!/bin/bash
      echo "Starting SonarQube scan..."
    env:
      - name: SONAR_PROJECT_KEY
        value: "hello"

containerTemplates:
  - name: test-container
    image: golang:latest
    inlineScript: |
      #!/bin/sh
      echo "testing"
    env:
      - name: GOPATH
        value: /go
  - name: lint-container
    inlineScript: |
      #!/bin/sh
      echo "formatting"
  - name: lint-container-2
    inlineScript: |
      #!/bin/sh
      echo "formatting"
  - name: lint-container-3
    inlineScript: |
      #!/bin/sh
      echo "formatting"
