steps:
  - name: Build Pipeline
    containerSet:
      containers:
      - name: Dockerfile Scan
        containerTemplate: choreo/dockerfile-scan@v1
      # - name: Docker Build
      #   containerTemplate: choreo/docker-build@v1
      - name: Vulnerability Scan
        containerTemplate: choreo/trivy-scan@v1
      - name: Test
        containerTemplate: test-container
      - name: Lint
        containerTemplate: lint-container

containerTemplates:
  - name: test-container
    image: golang:latest
    inlineScript: |
      #!/bin/sh
      echo "testing"
    env:
      - name: GOPATH
        value: /go
  - name: lint-container
    inlineScript: |
      #!/bin/sh
      echo "formatting"
