steps:
  - name: Build Steps
    containerSet:
      containers:
      - name: Buildpack Build
        containerTemplate: choreo/buildpack-build@v1
      - name: Vulnerability Scan
        containerTemplate: choreo/trivy-scan@v1
      - name: Test
        containerTemplate: test-container
      - name: Lint
        containerTemplate: lint-container
  - name: Static Code Analysis
    template: sonar-qube

templates:
  - name: sonar-qube
    inlineScript: |
      #!/bin/bash
      echo "Starting SonarQube scan..."
    env:
      - name: SONAR_PROJECT_KEY
        value: "hello"

containerTemplates:
  - name: test-container
    image: golang:latest
    inlineScript: |
      #!/bin/sh
      echo "Installing Go version $GO_VERSION and running tests..."
      go version
      cd $REPOSITORY_DIR
      make test
    env:
      - name: GO_VERSION
        value: "{{VARIABLES.GO_VERSION}}"
  - name: lint-container
    inlineScript: |
      #!/bin/bash
      echo "Installing Go version $GO_VERSION and running tests..."
      go version
      cd $REPOSITORY_DIR
      make lint-comprehensive
    env:
      - name: GO_VERSION
        value: "{{VARIABLES.GO_VERSION}}"
